kind: pipeline
type: docker
name: default

steps:
  - name: publish frontend
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mauriceo/viewtube-docs
      tags:
        - '1.0'
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push
